//! Bidirectional sync between the DAG and local filesystem.
//!
//! - **Forward sync**: local filesystem changes (from `FolderWatcher`) → engine operations
//! - **Reverse sync**: engine events (from remote peers) → local filesystem writes
//! - **Initial scan**: reconcile DAG state with local directory on startup

use std::collections::HashMap;
use std::io::Read;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use murmur_engine::{EngineEvent, MurmurEngine};
use murmur_types::{BlobHash, FileMetadata, FolderId, SyncMode};
use tracing::{debug, error, info, warn};

use crate::ignore::IgnoreFilter;
use crate::storage::Storage;
use crate::watcher::{EchoSuppressor, FolderEvent, FsEventKind};

/// Configuration for a synced folder on this device.
#[derive(Debug, Clone)]
pub struct SyncedFolder {
    /// The folder ID.
    pub folder_id: FolderId,
    /// Local directory path.
    pub local_path: PathBuf,
    /// Sync mode (read-write or read-only).
    pub mode: SyncMode,
}

// ---------------------------------------------------------------------------
// Reverse sync: DAG events → filesystem
// ---------------------------------------------------------------------------

/// Handle a reverse sync event: write or delete a file based on an engine event.
///
/// Returns `Ok(true)` if the event was handled, `Ok(false)` if it was not a
/// file-related event.
///
/// Before writing, checks whether the file already exists on disk with the
/// correct content (by hashing). This avoids redundant I/O when the event was
/// generated by this device's own forward sync.
pub fn handle_reverse_sync_event(
    event: &EngineEvent,
    folders: &HashMap<FolderId, SyncedFolder>,
    storage: &Storage,
    echo_suppressor: &EchoSuppressor,
) -> Result<bool> {
    match event {
        EngineEvent::FileSynced {
            blob_hash,
            folder_id,
            path,
        } => {
            if let Some(folder) = folders.get(folder_id) {
                reverse_sync_file(folder, path, *blob_hash, storage, echo_suppressor)?;
            }
            Ok(true)
        }
        EngineEvent::FileModified {
            folder_id,
            path,
            new_hash,
        } => {
            if let Some(folder) = folders.get(folder_id) {
                reverse_sync_file(folder, path, *new_hash, storage, echo_suppressor)?;
            }
            Ok(true)
        }
        EngineEvent::FileDeleted { folder_id, path } => {
            if let Some(folder) = folders.get(folder_id) {
                delete_file_from_disk(folder, path, echo_suppressor)?;
            }
            Ok(true)
        }
        _ => Ok(false),
    }
}

/// Write a blob to a local file, skipping if the file already has the correct content.
fn reverse_sync_file(
    folder: &SyncedFolder,
    relative_path: &str,
    blob_hash: BlobHash,
    storage: &Storage,
    echo_suppressor: &EchoSuppressor,
) -> Result<()> {
    let full_path = folder.local_path.join(relative_path);

    // Skip if the file already exists with the correct content.
    // This avoids redundant reads from encrypted blob storage and disk writes
    // when the event originated from this device's own forward sync.
    if full_path.is_file()
        && let Ok(existing_hash) = hash_file(&full_path)
        && existing_hash == blob_hash
    {
        debug!(
            path = %relative_path,
            "reverse sync: file already has correct content, skipping"
        );
        return Ok(());
    }

    if let Some(data) = storage.load_blob(blob_hash)? {
        write_file_to_disk(folder, relative_path, &data, echo_suppressor)?;
    } else {
        warn!(
            %blob_hash,
            path = relative_path,
            "blob not yet available for reverse sync"
        );
    }

    Ok(())
}

/// Write a blob to a local file path, creating parent directories as needed.
///
/// Marks the path for echo suppression so the filesystem watcher doesn't
/// re-sync the file we just wrote.
pub fn write_file_to_disk(
    folder: &SyncedFolder,
    relative_path: &str,
    data: &[u8],
    echo_suppressor: &EchoSuppressor,
) -> Result<()> {
    let full_path = folder.local_path.join(relative_path);

    // Create parent directories.
    if let Some(parent) = full_path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("create dirs for {}", full_path.display()))?;
    }

    // Mark for echo suppression BEFORE writing so the watcher sees it.
    echo_suppressor.mark_written(folder.folder_id, relative_path);

    std::fs::write(&full_path, data)
        .with_context(|| format!("write file {}", full_path.display()))?;

    debug!(path = %full_path.display(), size = data.len(), "wrote file to disk (reverse sync)");
    Ok(())
}

/// Delete a file from a local folder directory.
pub fn delete_file_from_disk(
    folder: &SyncedFolder,
    relative_path: &str,
    echo_suppressor: &EchoSuppressor,
) -> Result<()> {
    let full_path = folder.local_path.join(relative_path);

    if full_path.exists() {
        // Mark for echo suppression.
        echo_suppressor.mark_written(folder.folder_id, relative_path);

        std::fs::remove_file(&full_path)
            .with_context(|| format!("delete file {}", full_path.display()))?;

        debug!(path = %full_path.display(), "deleted file from disk (reverse sync)");

        // Clean up empty parent directories up to the folder root.
        let mut dir = full_path.parent();
        while let Some(parent) = dir {
            if parent == folder.local_path {
                break;
            }
            // Try to remove — fails silently if non-empty.
            if std::fs::remove_dir(parent).is_err() {
                break;
            }
            dir = parent.parent();
        }
    } else {
        debug!(
            path = %full_path.display(),
            "file already absent on disk (reverse sync delete)"
        );
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Forward sync: filesystem events → engine
// ---------------------------------------------------------------------------

/// Process a forward sync event (local filesystem change → engine operation).
///
/// Called from the main event loop when the watcher produces a debounced event.
pub fn handle_forward_sync_event(
    event: &FolderEvent,
    folders: &HashMap<FolderId, SyncedFolder>,
    engine: &mut MurmurEngine,
) -> Result<()> {
    let folder = match folders.get(&event.folder_id) {
        Some(f) => f,
        None => {
            warn!(
                folder_id = %hex::encode(event.folder_id.as_bytes()),
                "forward sync event for unknown folder"
            );
            return Ok(());
        }
    };

    // Read-only folders don't forward local changes.
    if folder.mode == SyncMode::ReadOnly {
        debug!(
            path = %event.relative_path,
            "skipping forward sync for read-only folder"
        );
        return Ok(());
    }

    let full_path = folder.local_path.join(&event.relative_path);

    match event.kind {
        FsEventKind::CreateOrModify => {
            if !full_path.is_file() {
                // Might be a directory creation or a file that was already deleted.
                return Ok(());
            }

            let state = engine.state();
            let key = (event.folder_id, event.relative_path.clone());
            let existing = state.files.get(&key).cloned();

            if let Some(existing_meta) = existing {
                // File already in DAG — read once, hash once, then pass to engine.
                let data = std::fs::read(&full_path)
                    .with_context(|| format!("read {}", full_path.display()))?;
                let current_hash = BlobHash::from_data(&data);

                if current_hash == existing_meta.blob_hash {
                    debug!(path = %event.relative_path, "file unchanged, skipping");
                    return Ok(());
                }

                info!(path = %event.relative_path, "forward sync: file modified");
                let size = data.len() as u64;
                let modified_at = file_modified_time(&full_path);
                let new_meta = FileMetadata {
                    blob_hash: current_hash,
                    folder_id: event.folder_id,
                    path: event.relative_path.clone(),
                    size,
                    mime_type: existing_meta.mime_type.clone(),
                    created_at: existing_meta.created_at,
                    modified_at,
                    device_origin: engine.device_id(),
                };
                engine.modify_file(event.folder_id, &event.relative_path, new_meta, data)?;
            } else {
                // New file → add.
                info!(path = %event.relative_path, "forward sync: new file");
                engine.add_file_streaming(event.folder_id, &event.relative_path, &full_path)?;
            }
        }
        FsEventKind::Remove => {
            let state = engine.state();
            let key = (event.folder_id, event.relative_path.clone());
            let in_dag = state.files.contains_key(&key);
            if in_dag {
                info!(path = %event.relative_path, "forward sync: file deleted");
                engine.delete_file(event.folder_id, &event.relative_path)?;
            }
        }
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Initial scan
// ---------------------------------------------------------------------------

/// Perform initial scan of a folder directory, reconciling local files with DAG state.
///
/// - Local file not in DAG → `add_file_streaming()` (read-write only)
/// - DAG file not on disk → write from blob store
/// - Both exist, same hash → skip
/// - Both exist, different hash → `modify_file()` (read-write only)
///
/// Applies the ignore filter so that `.DS_Store`, `.tmp` files, etc. are never
/// added to the DAG.
pub fn initial_scan(
    folder: &SyncedFolder,
    engine: &mut MurmurEngine,
    storage: &Storage,
    echo_suppressor: &EchoSuppressor,
    ignore_filter: &IgnoreFilter,
) -> Result<()> {
    let folder_id = folder.folder_id;

    info!(
        folder_id = %hex::encode(folder_id.as_bytes()),
        path = %folder.local_path.display(),
        "starting initial scan"
    );

    // Get current DAG state for this folder.
    let dag_files: HashMap<String, FileMetadata> = engine
        .folder_files(folder_id)
        .into_iter()
        .map(|m| (m.path.clone(), m))
        .collect();

    // Scan local directory.
    let local_files = scan_local_dir(&folder.local_path, &folder.local_path)?;

    // Local files not in DAG → add them (only if read-write).
    if folder.mode == SyncMode::ReadWrite {
        for (rel_path, full_path) in &local_files {
            // Apply ignore patterns — don't add OS cruft to DAG.
            if ignore_filter.is_ignored(Path::new(rel_path), false) {
                debug!(path = %rel_path, "initial scan: skipping ignored file");
                continue;
            }

            if !dag_files.contains_key(rel_path) {
                info!(path = %rel_path, "initial scan: local file not in DAG, adding");
                match engine.add_file_streaming(folder_id, rel_path, full_path) {
                    Ok(_entry) => {
                        debug!(path = %rel_path, "initial scan: added file to DAG");
                    }
                    Err(e) => {
                        error!(path = %rel_path, error = %e, "initial scan: failed to add file");
                    }
                }
            } else if let Some(dag_meta) = dag_files.get(rel_path) {
                // Both exist — read once, hash once, check for difference.
                let data = std::fs::read(full_path)
                    .with_context(|| format!("read {}", full_path.display()))?;
                let local_hash = BlobHash::from_data(&data);

                if local_hash != dag_meta.blob_hash {
                    info!(path = %rel_path, "initial scan: local file modified since last sync");
                    let size = data.len() as u64;
                    let modified_at = file_modified_time(full_path);
                    let new_meta = FileMetadata {
                        blob_hash: local_hash,
                        folder_id,
                        path: rel_path.clone(),
                        size,
                        mime_type: dag_meta.mime_type.clone(),
                        created_at: dag_meta.created_at,
                        modified_at,
                        device_origin: engine.device_id(),
                    };
                    match engine.modify_file(folder_id, rel_path, new_meta, data) {
                        Ok(_entry) => {
                            debug!(path = %rel_path, "initial scan: updated file in DAG");
                        }
                        Err(e) => {
                            error!(path = %rel_path, error = %e, "initial scan: failed to modify file");
                        }
                    }
                }
            }
        }
    }

    // DAG files not on local disk → write from blob store.
    for (rel_path, dag_meta) in &dag_files {
        if !local_files.contains_key(rel_path) {
            info!(path = %rel_path, "initial scan: DAG file not on disk, writing");
            if let Some(data) = storage.load_blob(dag_meta.blob_hash)? {
                write_file_to_disk(folder, rel_path, &data, echo_suppressor)?;
            } else {
                warn!(
                    path = %rel_path,
                    blob_hash = %dag_meta.blob_hash,
                    "initial scan: blob not available in store"
                );
            }
        }
    }

    info!(
        folder_id = %hex::encode(folder_id.as_bytes()),
        local_count = local_files.len(),
        dag_count = dag_files.len(),
        "initial scan complete"
    );

    Ok(())
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Scan a local directory recursively, returning a map of relative_path → full_path.
///
/// Returns all regular files; ignore-pattern filtering is the caller's
/// responsibility.
fn scan_local_dir(root: &Path, dir: &Path) -> Result<HashMap<String, PathBuf>> {
    let mut result = HashMap::new();

    if !dir.exists() {
        return Ok(result);
    }

    for entry in std::fs::read_dir(dir).with_context(|| format!("read dir {}", dir.display()))? {
        let entry = entry?;
        let path = entry.path();
        let file_type = entry.file_type()?;

        if file_type.is_dir() {
            let sub = scan_local_dir(root, &path)?;
            result.extend(sub);
        } else if file_type.is_file()
            && let Ok(rel) = path.strip_prefix(root)
        {
            let rel_str = rel.to_string_lossy().replace('\\', "/");
            if !rel_str.is_empty() {
                result.insert(rel_str, path);
            }
        }
    }

    Ok(result)
}

/// Compute blake3 hash of a file (streaming, 64 KiB buffers).
fn hash_file(path: &Path) -> Result<BlobHash> {
    let mut file = std::fs::File::open(path).with_context(|| format!("open {}", path.display()))?;
    let mut hasher = blake3::Hasher::new();
    let mut buf = [0u8; 65536];
    loop {
        let n = file.read(&mut buf)?;
        if n == 0 {
            break;
        }
        hasher.update(&buf[..n]);
    }
    Ok(BlobHash::from_bytes(*hasher.finalize().as_bytes()))
}

/// Get a file's OS modification time as seconds since Unix epoch.
fn file_modified_time(path: &Path) -> u64 {
    std::fs::metadata(path)
        .ok()
        .and_then(|m| m.modified().ok())
        .and_then(|t| t.duration_since(std::time::UNIX_EPOCH).ok())
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_scan_local_dir() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path();

        std::fs::create_dir_all(root.join("photos")).unwrap();
        std::fs::write(root.join("readme.txt"), "hello").unwrap();
        std::fs::write(root.join("photos/img001.jpg"), "image data").unwrap();
        std::fs::write(root.join("photos/img002.jpg"), "image data 2").unwrap();

        let result = scan_local_dir(root, root).unwrap();
        assert_eq!(result.len(), 3);
        assert!(result.contains_key("readme.txt"));
        assert!(result.contains_key("photos/img001.jpg"));
        assert!(result.contains_key("photos/img002.jpg"));
    }

    #[test]
    fn test_scan_empty_dir() {
        let dir = tempfile::tempdir().unwrap();
        let result = scan_local_dir(dir.path(), dir.path()).unwrap();
        assert!(result.is_empty());
    }

    #[test]
    fn test_scan_nonexistent_dir() {
        let result = scan_local_dir(Path::new("/nonexistent"), Path::new("/nonexistent")).unwrap();
        assert!(result.is_empty());
    }

    #[test]
    fn test_hash_file() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("test.bin");
        let data = b"hello world";
        std::fs::write(&path, data).unwrap();

        let hash = hash_file(&path).unwrap();
        let expected = BlobHash::from_data(data);
        assert_eq!(hash, expected);
    }

    #[test]
    fn test_write_file_to_disk() {
        let dir = tempfile::tempdir().unwrap();
        let suppressor = EchoSuppressor::new();
        let folder = SyncedFolder {
            folder_id: FolderId::from_bytes([1u8; 32]),
            local_path: dir.path().to_path_buf(),
            mode: SyncMode::ReadWrite,
        };

        write_file_to_disk(&folder, "subdir/file.txt", b"content", &suppressor).unwrap();

        let full_path = dir.path().join("subdir/file.txt");
        assert!(full_path.exists());
        assert_eq!(std::fs::read_to_string(&full_path).unwrap(), "content");

        // Should be echo-suppressed.
        assert!(suppressor.is_echo(folder.folder_id, "subdir/file.txt"));
    }

    #[test]
    fn test_delete_file_from_disk() {
        let dir = tempfile::tempdir().unwrap();
        let suppressor = EchoSuppressor::new();
        let folder = SyncedFolder {
            folder_id: FolderId::from_bytes([1u8; 32]),
            local_path: dir.path().to_path_buf(),
            mode: SyncMode::ReadWrite,
        };

        let subdir = dir.path().join("subdir");
        std::fs::create_dir_all(&subdir).unwrap();
        std::fs::write(subdir.join("file.txt"), "content").unwrap();

        delete_file_from_disk(&folder, "subdir/file.txt", &suppressor).unwrap();

        assert!(!subdir.join("file.txt").exists());
        // Empty subdir should be cleaned up.
        assert!(!subdir.exists());
    }

    #[test]
    fn test_delete_nonexistent_file() {
        let dir = tempfile::tempdir().unwrap();
        let suppressor = EchoSuppressor::new();
        let folder = SyncedFolder {
            folder_id: FolderId::from_bytes([1u8; 32]),
            local_path: dir.path().to_path_buf(),
            mode: SyncMode::ReadWrite,
        };

        // Should not error.
        delete_file_from_disk(&folder, "nonexistent.txt", &suppressor).unwrap();
    }

    #[test]
    fn test_reverse_sync_skips_existing_correct_file() {
        let dir = tempfile::tempdir().unwrap();
        let _folder = SyncedFolder {
            folder_id: FolderId::from_bytes([1u8; 32]),
            local_path: dir.path().to_path_buf(),
            mode: SyncMode::ReadWrite,
        };

        // Write a file that already has the expected content.
        let data = b"hello world";
        let full_path = dir.path().join("test.txt");
        std::fs::write(&full_path, data).unwrap();

        let blob_hash = BlobHash::from_data(data);
        let _suppressor = EchoSuppressor::new();

        // reverse_sync_file should skip since content matches.
        // We can't easily test with real Storage, but we can test the hash-check path:
        assert!(full_path.is_file());
        let existing_hash = hash_file(&full_path).unwrap();
        assert_eq!(existing_hash, blob_hash);
    }

    #[test]
    fn test_file_modified_time() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("test.txt");
        std::fs::write(&path, "hello").unwrap();

        let mtime = file_modified_time(&path);
        assert!(mtime > 0);
    }
}
