//! UniFFI FFI bindings for Murmur.
//!
//! Exposes [`murmur-engine`] to Android and iOS via a thin C-compatible FFI
//! layer generated by [UniFFI](https://mozilla.github.io/uniffi-rs/).  The
//! FFI surface is fully **synchronous** — all async work runs on a `tokio`
//! runtime owned by [`MurmurHandle`].
//!
//! # Mobile usage (generated Kotlin)
//!
//! ```kotlin
//! val handle = MurmurKt.createNetwork("My Phone", mnemonic, callbacks)
//! handle.start()
//! handle.approveDevice(deviceIdHex, "full")
//! ```

uniffi::setup_scaffolding!("murmur");

use std::sync::{Arc, Mutex};

use murmur_dag::DagEntry;
use murmur_engine::{EngineEvent, MurmurEngine, PlatformCallbacks};
use murmur_seed::WordCount;
use murmur_seed::{DeviceKeyPair, NetworkIdentity, generate_mnemonic, parse_mnemonic};
use murmur_types::{AccessScope, BlobHash, DeviceId, DeviceRole, FileMetadata};
use tracing::debug;

// ---------------------------------------------------------------------------
// Error type
// ---------------------------------------------------------------------------

/// Errors returned across the FFI boundary.
#[derive(Debug, thiserror::Error, uniffi::Error)]
pub enum FfiError {
    /// The mnemonic phrase is invalid.
    #[error("invalid mnemonic: {message}")]
    InvalidMnemonic { message: String },
    /// A device ID hex string could not be decoded.
    #[error("invalid device ID: {message}")]
    InvalidDeviceId { message: String },
    /// A general engine operation failed.
    #[error("operation failed: {message}")]
    OperationFailed { message: String },
}

impl From<murmur_engine::EngineError> for FfiError {
    fn from(e: murmur_engine::EngineError) -> Self {
        FfiError::OperationFailed {
            message: e.to_string(),
        }
    }
}

impl From<murmur_dag::DagError> for FfiError {
    fn from(e: murmur_dag::DagError) -> Self {
        FfiError::OperationFailed {
            message: e.to_string(),
        }
    }
}

// ---------------------------------------------------------------------------
// FFI wrapper types
// ---------------------------------------------------------------------------

/// Device information across the FFI boundary.
#[derive(Debug, Clone, uniffi::Record)]
pub struct DeviceInfoFfi {
    /// Raw 32-byte device ID.
    pub device_id: Vec<u8>,
    /// Human-readable device name.
    pub name: String,
    /// Role string: `"source"`, `"backup"`, or `"full"`.
    pub role: String,
    /// Whether this device has been approved.
    pub approved: bool,
    /// Raw 32-byte approving device ID, or `None`.
    pub approved_by: Option<Vec<u8>>,
    /// HLC timestamp at which the device joined.
    pub joined_at: u64,
}

/// File metadata across the FFI boundary.
#[derive(Debug, Clone, uniffi::Record)]
pub struct FileMetadataFfi {
    /// Raw 32-byte blake3 content hash.
    pub blob_hash: Vec<u8>,
    /// File name.
    pub filename: String,
    /// File size in bytes.
    pub size: u64,
    /// MIME type, if known.
    pub mime_type: Option<String>,
    /// Filesystem creation timestamp (Unix seconds).
    pub created_at: u64,
    /// Raw 32-byte originating device ID.
    pub device_origin: Vec<u8>,
}

/// Access scope across the FFI boundary.
#[derive(Debug, Clone, uniffi::Enum)]
pub enum AccessScopeFfi {
    /// Access to all files.
    AllFiles,
    /// Access to files whose path starts with `prefix`.
    FilesByPrefix { prefix: String },
    /// Access to a single file identified by its blake3 hash.
    SingleFile { blob_hash: Vec<u8> },
}

/// Engine events pushed to the platform.
#[derive(Debug, Clone, uniffi::Enum)]
pub enum MurmurEventFfi {
    /// A device sent a join request.
    DeviceJoinRequested { device_id: Vec<u8>, name: String },
    /// A device was approved.
    DeviceApproved { device_id: Vec<u8>, role: String },
    /// A device was revoked.
    DeviceRevoked { device_id: Vec<u8> },
    /// A file was synced.
    FileSynced {
        blob_hash: Vec<u8>,
        filename: String,
    },
    /// A blob was received.
    BlobReceived { blob_hash: Vec<u8> },
    /// A remote device requested access to local files.
    AccessRequested { from_device_id: Vec<u8> },
    /// Access was granted to a device.
    AccessGranted { to_device_id: Vec<u8> },
    /// The DAG was synced with new entries.
    DagSynced { new_entries: u64 },
    /// This device created a new network.
    NetworkCreated { device_id: Vec<u8> },
    /// This device joined an existing network.
    NetworkJoined { device_id: Vec<u8> },
    /// Progress update for an in-flight blob transfer.
    BlobTransferProgress {
        blob_hash: Vec<u8>,
        bytes_transferred: u64,
        total_bytes: u64,
    },
}

// ---------------------------------------------------------------------------
// Conversion helpers
// ---------------------------------------------------------------------------

fn role_to_string(role: DeviceRole) -> String {
    match role {
        DeviceRole::Source => "source".to_string(),
        DeviceRole::Backup => "backup".to_string(),
        DeviceRole::Full => "full".to_string(),
    }
}

fn role_from_string(s: &str) -> DeviceRole {
    match s {
        "source" => DeviceRole::Source,
        "backup" => DeviceRole::Backup,
        _ => DeviceRole::Full,
    }
}

fn device_info_to_ffi(d: &murmur_types::DeviceInfo) -> DeviceInfoFfi {
    DeviceInfoFfi {
        device_id: d.device_id.as_bytes().to_vec(),
        name: d.name.clone(),
        role: role_to_string(d.role),
        approved: d.approved,
        approved_by: d.approved_by.map(|id| id.as_bytes().to_vec()),
        joined_at: d.joined_at,
    }
}

fn engine_event_to_ffi(event: EngineEvent) -> MurmurEventFfi {
    match event {
        EngineEvent::DeviceJoinRequested { device_id, name } => {
            MurmurEventFfi::DeviceJoinRequested {
                device_id: device_id.as_bytes().to_vec(),
                name,
            }
        }
        EngineEvent::DeviceApproved { device_id, role } => MurmurEventFfi::DeviceApproved {
            device_id: device_id.as_bytes().to_vec(),
            role: role_to_string(role),
        },
        EngineEvent::DeviceRevoked { device_id } => MurmurEventFfi::DeviceRevoked {
            device_id: device_id.as_bytes().to_vec(),
        },
        EngineEvent::FileSynced {
            blob_hash,
            filename,
        } => MurmurEventFfi::FileSynced {
            blob_hash: blob_hash.as_bytes().to_vec(),
            filename,
        },
        EngineEvent::BlobReceived { blob_hash } => MurmurEventFfi::BlobReceived {
            blob_hash: blob_hash.as_bytes().to_vec(),
        },
        EngineEvent::AccessRequested { from } => MurmurEventFfi::AccessRequested {
            from_device_id: from.as_bytes().to_vec(),
        },
        EngineEvent::AccessGranted { to } => MurmurEventFfi::AccessGranted {
            to_device_id: to.as_bytes().to_vec(),
        },
        EngineEvent::DagSynced { new_entries } => MurmurEventFfi::DagSynced {
            new_entries: new_entries as u64,
        },
        EngineEvent::NetworkCreated { device_id } => MurmurEventFfi::NetworkCreated {
            device_id: device_id.as_bytes().to_vec(),
        },
        EngineEvent::NetworkJoined { device_id } => MurmurEventFfi::NetworkJoined {
            device_id: device_id.as_bytes().to_vec(),
        },
        EngineEvent::BlobTransferProgress {
            blob_hash,
            bytes_transferred,
            total_bytes,
        } => MurmurEventFfi::BlobTransferProgress {
            blob_hash: blob_hash.as_bytes().to_vec(),
            bytes_transferred,
            total_bytes,
        },
    }
}

fn parse_device_id(hex_str: &str) -> Result<DeviceId, FfiError> {
    let bytes = hex::decode(hex_str).map_err(|e| FfiError::InvalidDeviceId {
        message: e.to_string(),
    })?;
    let arr: [u8; 32] = bytes.try_into().map_err(|_| FfiError::InvalidDeviceId {
        message: "expected 32 bytes (64 hex chars)".to_string(),
    })?;
    Ok(DeviceId::from_bytes(arr))
}

fn access_scope_from_ffi(scope: AccessScopeFfi) -> Result<AccessScope, FfiError> {
    match scope {
        AccessScopeFfi::AllFiles => Ok(AccessScope::AllFiles),
        AccessScopeFfi::FilesByPrefix { prefix } => Ok(AccessScope::FilesByPrefix(prefix)),
        AccessScopeFfi::SingleFile { blob_hash } => {
            let arr: [u8; 32] = blob_hash
                .try_into()
                .map_err(|_| FfiError::OperationFailed {
                    message: "blob_hash must be 32 bytes".to_string(),
                })?;
            Ok(AccessScope::SingleFile(BlobHash::from_bytes(arr)))
        }
    }
}

// ---------------------------------------------------------------------------
// Platform callbacks bridge
// ---------------------------------------------------------------------------

/// Callback interface implemented by the mobile platform (Kotlin / Swift).
///
/// UniFFI generates the language-specific implementation stubs.  The platform
/// code provides the storage/persistence; the engine calls these when it
/// produces data that must be persisted or when a noteworthy event occurs.
#[uniffi::export(callback_interface)]
pub trait FfiPlatformCallbacks: Send + Sync {
    /// Persist a new DAG entry (postcard-encoded bytes).
    fn on_dag_entry(&self, entry_bytes: Vec<u8>);

    /// Store a received blob (`blob_hash` is the raw 32-byte blake3 hash).
    fn on_blob_received(&self, blob_hash: Vec<u8>, data: Vec<u8>);

    /// Load a blob for transfer.  Returns `None` if unavailable locally.
    fn on_blob_needed(&self, blob_hash: Vec<u8>) -> Option<Vec<u8>>;

    /// Notify the platform of an engine event.
    fn on_event(&self, event: MurmurEventFfi);
}

/// Shared, ref-counted platform callbacks used internally.
type SharedCallbacks = Arc<dyn FfiPlatformCallbacks>;

/// Bridges [`SharedCallbacks`] → [`murmur_engine::PlatformCallbacks`].
struct CallbacksBridge {
    inner: SharedCallbacks,
}

impl PlatformCallbacks for CallbacksBridge {
    fn on_dag_entry(&self, entry_bytes: Vec<u8>) {
        self.inner.on_dag_entry(entry_bytes);
    }
    fn on_blob_received(&self, blob_hash: BlobHash, data: Vec<u8>) {
        self.inner
            .on_blob_received(blob_hash.as_bytes().to_vec(), data);
    }
    fn on_blob_needed(&self, blob_hash: BlobHash) -> Option<Vec<u8>> {
        self.inner.on_blob_needed(blob_hash.as_bytes().to_vec())
    }
    fn on_event(&self, event: EngineEvent) {
        self.inner.on_event(engine_event_to_ffi(event));
    }
}

// ---------------------------------------------------------------------------
// MurmurHandle
// ---------------------------------------------------------------------------

/// A running Murmur engine instance.
///
/// Thread-safe: all methods take `&self` with interior mutability.
/// Keep alive for the duration of the session.
#[derive(uniffi::Object)]
pub struct MurmurHandle {
    inner: Mutex<MurmurEngine>,
    /// Tokio runtime for background async work.
    rt: tokio::runtime::Runtime,
    /// Stored so `fetch_blob` can call `on_blob_needed` directly.
    ffi_callbacks: SharedCallbacks,
}

#[uniffi::export]
impl MurmurHandle {
    /// Load a persisted DAG entry on startup (call once per stored entry).
    pub fn load_dag_entry(&self, entry_bytes: Vec<u8>) -> Result<(), FfiError> {
        self.inner.lock().unwrap().load_entry_bytes(&entry_bytes)?;
        Ok(())
    }

    /// Start background network activity.  Idempotent.
    pub fn start(&self) {
        // The tokio runtime is ready for spawning async tasks (gossip, sync).
        let _handle = self.rt.handle();
        debug!("MurmurHandle::start");
    }

    /// Stop background network activity.  Idempotent.
    pub fn stop(&self) {
        debug!("MurmurHandle::stop");
    }

    /// Approve a pending device.  `role` is `"source"`, `"backup"`, or `"full"`.
    pub fn approve_device(&self, device_id_hex: String, role: String) -> Result<(), FfiError> {
        let device_id = parse_device_id(&device_id_hex)?;
        self.inner
            .lock()
            .unwrap()
            .approve_device(device_id, role_from_string(&role))?;
        Ok(())
    }

    /// Revoke an existing device.
    pub fn revoke_device(&self, device_id_hex: String) -> Result<(), FfiError> {
        let device_id = parse_device_id(&device_id_hex)?;
        self.inner.lock().unwrap().revoke_device(device_id)?;
        Ok(())
    }

    /// All known devices (approved and pending).
    pub fn list_devices(&self) -> Vec<DeviceInfoFfi> {
        self.inner
            .lock()
            .unwrap()
            .list_devices()
            .iter()
            .map(device_info_to_ffi)
            .collect()
    }

    /// Devices that sent a join request but are not yet approved.
    pub fn pending_requests(&self) -> Vec<DeviceInfoFfi> {
        self.inner
            .lock()
            .unwrap()
            .pending_requests()
            .iter()
            .map(device_info_to_ffi)
            .collect()
    }

    /// This device's ID as a 64-character lowercase hex string.
    pub fn device_id_hex(&self) -> String {
        hex::encode(self.inner.lock().unwrap().device_id().as_bytes())
    }

    /// Add a file.  `blob_hash` must be blake3(`data`).
    pub fn add_file(
        &self,
        blob_hash: Vec<u8>,
        metadata: FileMetadataFfi,
        data: Vec<u8>,
    ) -> Result<(), FfiError> {
        let hash_arr: [u8; 32] = blob_hash
            .try_into()
            .map_err(|_| FfiError::OperationFailed {
                message: "blob_hash must be 32 bytes".to_string(),
            })?;
        let origin_arr: [u8; 32] =
            metadata
                .device_origin
                .try_into()
                .map_err(|_| FfiError::OperationFailed {
                    message: "device_origin must be 32 bytes".to_string(),
                })?;
        let file_meta = FileMetadata {
            blob_hash: BlobHash::from_bytes(hash_arr),
            filename: metadata.filename,
            size: metadata.size,
            mime_type: metadata.mime_type,
            created_at: metadata.created_at,
            device_origin: DeviceId::from_bytes(origin_arr),
        };
        self.inner.lock().unwrap().add_file(file_meta, data)?;
        Ok(())
    }

    /// Request access to files on another device (emits `AccessRequested` event).
    pub fn request_access(
        &self,
        device_id_hex: String,
        scope: AccessScopeFfi,
    ) -> Result<(), FfiError> {
        let _to_id = parse_device_id(&device_id_hex)?;
        let _scope = access_scope_from_ffi(scope)?;
        let from_id = self.inner.lock().unwrap().device_id();
        self.ffi_callbacks
            .on_event(MurmurEventFfi::AccessRequested {
                from_device_id: from_id.as_bytes().to_vec(),
            });
        Ok(())
    }

    /// Fetch a blob from local storage via the platform callback.
    pub fn fetch_blob(&self, blob_hash: Vec<u8>) -> Option<Vec<u8>> {
        self.ffi_callbacks.on_blob_needed(blob_hash)
    }

    /// Apply remote DAG entries received from a peer (each element is postcard bytes).
    pub fn receive_sync_entries(&self, entries: Vec<Vec<u8>>) -> Result<(), FfiError> {
        let dag_entries: Result<Vec<DagEntry>, FfiError> = entries
            .iter()
            .map(|b| DagEntry::from_bytes(b).map_err(FfiError::from))
            .collect();
        self.inner
            .lock()
            .unwrap()
            .receive_sync_entries(dag_entries?)?;
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// Constructor functions (FFI namespace entry points)
// ---------------------------------------------------------------------------

/// Generate a fresh 12-word BIP39 mnemonic suitable for creating a new network.
#[uniffi::export]
pub fn new_mnemonic() -> String {
    generate_mnemonic(WordCount::Twelve).to_string()
}

/// Create a new Murmur network.  The first device is auto-approved (`Full` role).
///
/// `callbacks` is owned by the handle and must remain valid for the handle's lifetime.
/// UniFFI passes it as a `Box<dyn FfiPlatformCallbacks>`.
#[uniffi::export]
pub fn create_network(
    device_name: String,
    mnemonic: String,
    callbacks: Box<dyn FfiPlatformCallbacks>,
) -> Result<Arc<MurmurHandle>, FfiError> {
    let mn = parse_mnemonic(&mnemonic).map_err(|e| FfiError::InvalidMnemonic {
        message: e.to_string(),
    })?;
    let identity = NetworkIdentity::from_mnemonic(&mn, "");
    let signing_key = identity.first_device_signing_key().clone();
    let device_id = identity.first_device_id();

    // Convert Box → Arc so we can share between CallbacksBridge and MurmurHandle.
    let shared: SharedCallbacks = Arc::from(callbacks);
    let bridge = Arc::new(CallbacksBridge {
        inner: Arc::clone(&shared),
    });
    let engine = MurmurEngine::create_network(
        device_id,
        signing_key,
        device_name,
        DeviceRole::Full,
        bridge,
    );
    let rt = tokio::runtime::Runtime::new().map_err(|e| FfiError::OperationFailed {
        message: format!("failed to create tokio runtime: {e}"),
    })?;
    Ok(Arc::new(MurmurHandle {
        inner: Mutex::new(engine),
        rt,
        ffi_callbacks: shared,
    }))
}

/// Join an existing Murmur network.  A fresh random device keypair is generated;
/// the device starts in the *pending* (unapproved) state.
#[uniffi::export]
pub fn join_network(
    device_name: String,
    mnemonic: String,
    callbacks: Box<dyn FfiPlatformCallbacks>,
) -> Result<Arc<MurmurHandle>, FfiError> {
    parse_mnemonic(&mnemonic).map_err(|e| FfiError::InvalidMnemonic {
        message: e.to_string(),
    })?;
    let kp = DeviceKeyPair::generate();
    let shared: SharedCallbacks = Arc::from(callbacks);
    let bridge = Arc::new(CallbacksBridge {
        inner: Arc::clone(&shared),
    });
    let engine = MurmurEngine::join_network(
        kp.device_id(),
        kp.signing_key().clone(),
        device_name,
        bridge,
    );
    let rt = tokio::runtime::Runtime::new().map_err(|e| FfiError::OperationFailed {
        message: format!("failed to create tokio runtime: {e}"),
    })?;
    Ok(Arc::new(MurmurHandle {
        inner: Mutex::new(engine),
        rt,
        ffi_callbacks: shared,
    }))
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Mutex as StdMutex;

    // -----------------------------------------------------------------------
    // Test helpers
    // -----------------------------------------------------------------------

    /// Shared state inspected by tests after the Box<dyn FfiPlatformCallbacks>
    /// has been consumed by the handle constructor.
    #[derive(Default)]
    struct CallbackState {
        dag_entries: StdMutex<Vec<Vec<u8>>>,
        blobs: StdMutex<Vec<(Vec<u8>, Vec<u8>)>>,
        events: StdMutex<Vec<MurmurEventFfi>>,
    }

    /// A `FfiPlatformCallbacks` implementation backed by `Arc<CallbackState>`.
    struct TestCallbacks(Arc<CallbackState>);

    impl FfiPlatformCallbacks for TestCallbacks {
        fn on_dag_entry(&self, entry_bytes: Vec<u8>) {
            self.0.dag_entries.lock().unwrap().push(entry_bytes);
        }
        fn on_blob_received(&self, blob_hash: Vec<u8>, data: Vec<u8>) {
            self.0.blobs.lock().unwrap().push((blob_hash, data));
        }
        fn on_blob_needed(&self, blob_hash: Vec<u8>) -> Option<Vec<u8>> {
            self.0
                .blobs
                .lock()
                .unwrap()
                .iter()
                .find(|(h, _)| *h == blob_hash)
                .map(|(_, d)| d.clone())
        }
        fn on_event(&self, event: MurmurEventFfi) {
            self.0.events.lock().unwrap().push(event);
        }
    }

    fn test_mnemonic() -> String {
        "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
            .to_string()
    }

    /// Build a handle + keep the callback state for inspection.
    fn make_handle() -> (Arc<MurmurHandle>, Arc<CallbackState>) {
        let state = Arc::new(CallbackState::default());
        let cb = Box::new(TestCallbacks(Arc::clone(&state)));
        let handle = create_network("TestDevice".to_string(), test_mnemonic(), cb).unwrap();
        (handle, state)
    }

    fn valid_file_meta(handle: &MurmurHandle, content: &[u8]) -> (Vec<u8>, FileMetadataFfi) {
        let blob_hash = BlobHash::from_data(content).as_bytes().to_vec();
        let device_origin = hex::decode(handle.device_id_hex()).unwrap();
        let meta = FileMetadataFfi {
            blob_hash: blob_hash.clone(),
            filename: "test.txt".to_string(),
            size: content.len() as u64,
            mime_type: None,
            created_at: 0,
            device_origin,
        };
        (blob_hash, meta)
    }

    // -----------------------------------------------------------------------
    // 1 — FFI wrapper type roundtrips
    // -----------------------------------------------------------------------

    #[test]
    fn test_device_info_ffi_fields() {
        let id = [1u8; 32];
        let info = DeviceInfoFfi {
            device_id: id.to_vec(),
            name: "Phone".to_string(),
            role: "source".to_string(),
            approved: true,
            approved_by: Some([2u8; 32].to_vec()),
            joined_at: 42,
        };
        assert_eq!(info.device_id, id);
        assert_eq!(info.name, "Phone");
        assert_eq!(info.role, "source");
        assert!(info.approved);
        assert_eq!(info.approved_by.unwrap(), [2u8; 32]);
        assert_eq!(info.joined_at, 42);
    }

    #[test]
    fn test_file_metadata_ffi_fields() {
        let hash = [0xabu8; 32];
        let origin = [0xcdu8; 32];
        let meta = FileMetadataFfi {
            blob_hash: hash.to_vec(),
            filename: "photo.jpg".to_string(),
            size: 1024,
            mime_type: Some("image/jpeg".to_string()),
            created_at: 9999,
            device_origin: origin.to_vec(),
        };
        assert_eq!(meta.blob_hash, hash);
        assert_eq!(meta.filename, "photo.jpg");
        assert_eq!(meta.size, 1024);
        assert_eq!(meta.mime_type.unwrap(), "image/jpeg");
        assert_eq!(meta.device_origin, origin);
    }

    #[test]
    fn test_access_scope_ffi_variants() {
        assert!(matches!(AccessScopeFfi::AllFiles, AccessScopeFfi::AllFiles));
        let prefix = AccessScopeFfi::FilesByPrefix {
            prefix: "photos/".to_string(),
        };
        if let AccessScopeFfi::FilesByPrefix { prefix: p } = prefix {
            assert_eq!(p, "photos/");
        } else {
            panic!("wrong variant");
        }
        let single = AccessScopeFfi::SingleFile {
            blob_hash: vec![0u8; 32],
        };
        assert!(matches!(single, AccessScopeFfi::SingleFile { .. }));
    }

    // -----------------------------------------------------------------------
    // 2 — create_network returns a valid handle
    // -----------------------------------------------------------------------

    #[test]
    fn test_create_network_valid_handle() {
        let (handle, _state) = make_handle();
        assert_eq!(handle.device_id_hex().len(), 64);
        let devices = handle.list_devices();
        assert_eq!(devices.len(), 1);
        assert!(devices[0].approved);
        assert_eq!(devices[0].role, "full");
    }

    // -----------------------------------------------------------------------
    // 3 — join_network with invalid mnemonic → error, not panic
    // -----------------------------------------------------------------------

    #[test]
    fn test_join_network_invalid_mnemonic() {
        let cb = Box::new(TestCallbacks(Arc::new(CallbackState::default())));
        let result = join_network("Phone".to_string(), "not valid words".to_string(), cb);
        assert!(matches!(result, Err(FfiError::InvalidMnemonic { .. })));
    }

    // -----------------------------------------------------------------------
    // 4 — approve_device bad input → error, not panic
    // -----------------------------------------------------------------------

    #[test]
    fn test_approve_device_non_hex_error() {
        let (handle, _state) = make_handle();
        let result = handle.approve_device("ZZZZ-not-hex!".to_string(), "full".to_string());
        assert!(matches!(result, Err(FfiError::InvalidDeviceId { .. })));
    }

    #[test]
    fn test_approve_device_short_hex_error() {
        let (handle, _state) = make_handle();
        // 16 bytes → 32 hex chars — valid hex but wrong length.
        let result = handle.approve_device(
            "deadbeefdeadbeefdeadbeefdeadbeef".to_string(),
            "full".to_string(),
        );
        assert!(matches!(result, Err(FfiError::InvalidDeviceId { .. })));
    }

    // -----------------------------------------------------------------------
    // 5 — add_file invokes on_dag_entry
    // -----------------------------------------------------------------------

    #[test]
    fn test_add_file_triggers_on_dag_entry() {
        let (handle, state) = make_handle();
        let before = state.dag_entries.lock().unwrap().len();
        let (blob_hash, meta) = valid_file_meta(&handle, b"hello world");
        handle
            .add_file(blob_hash, meta, b"hello world".to_vec())
            .unwrap();
        assert!(state.dag_entries.lock().unwrap().len() > before);
    }

    // -----------------------------------------------------------------------
    // 6 — fetch_blob delegates to on_blob_needed
    // -----------------------------------------------------------------------

    #[test]
    fn test_fetch_blob_absent_returns_none() {
        let (handle, _state) = make_handle();
        assert_eq!(handle.fetch_blob(vec![0u8; 32]), None);
    }

    #[test]
    fn test_fetch_blob_present_after_add_file() {
        let (handle, _state) = make_handle();
        let content = b"some content";
        let (blob_hash, meta) = valid_file_meta(&handle, content);
        handle
            .add_file(blob_hash.clone(), meta, content.to_vec())
            .unwrap();
        assert_eq!(handle.fetch_blob(blob_hash), Some(content.to_vec()));
    }

    // -----------------------------------------------------------------------
    // 7 — list_devices after approve
    // -----------------------------------------------------------------------

    #[test]
    fn test_list_devices_after_approve() {
        let (handle1, _state1) = make_handle();

        // handle2 joins and emits a join-request entry.
        let state2 = Arc::new(CallbackState::default());
        let handle2 = join_network(
            "Tablet".to_string(),
            test_mnemonic(),
            Box::new(TestCallbacks(Arc::clone(&state2))),
        )
        .unwrap();
        let id2 = handle2.device_id_hex();

        // Feed handle2's join-request into handle1.
        let join_bytes = state2.dag_entries.lock().unwrap().clone();
        handle1.receive_sync_entries(join_bytes).unwrap();

        // Approve via FFI.
        handle1
            .approve_device(id2.clone(), "source".to_string())
            .unwrap();

        let found = handle1
            .list_devices()
            .into_iter()
            .find(|d| hex::encode(&d.device_id) == id2);
        assert!(found.is_some());
        let dev = found.unwrap();
        assert!(dev.approved);
        assert_eq!(dev.role, "source");
    }

    // -----------------------------------------------------------------------
    // 8 — thread safety
    // -----------------------------------------------------------------------

    #[test]
    fn test_concurrent_reads_no_deadlock() {
        use std::thread;
        let (handle, _state) = make_handle();
        let threads: Vec<_> = (0..8)
            .map(|_| {
                let h = Arc::clone(&handle);
                thread::spawn(move || {
                    let _ = h.list_devices();
                    let _ = h.pending_requests();
                    let _ = h.device_id_hex();
                })
            })
            .collect();
        for t in threads {
            t.join().expect("thread panicked");
        }
    }

    // -----------------------------------------------------------------------
    // 9 — start + stop lifecycle
    // -----------------------------------------------------------------------

    #[test]
    fn test_start_stop_lifecycle() {
        let (handle, _state) = make_handle();
        handle.start();
        handle.start(); // idempotent
        handle.stop();
        handle.stop(); // idempotent
        // Still usable after stop.
        assert_eq!(handle.list_devices().len(), 1);
    }

    // -----------------------------------------------------------------------
    // 10 — load_dag_entry on startup
    // -----------------------------------------------------------------------

    #[test]
    fn test_load_dag_entry_restores_state() {
        let (handle1, state1) = make_handle();
        let id1 = handle1.device_id_hex();

        let saved: Vec<Vec<u8>> = state1.dag_entries.lock().unwrap().clone();
        assert!(!saved.is_empty());

        // Replay entries into a fresh handle2.
        let handle2 = join_network(
            "Phone".to_string(),
            test_mnemonic(),
            Box::new(TestCallbacks(Arc::new(CallbackState::default()))),
        )
        .unwrap();
        for bytes in saved {
            handle2.load_dag_entry(bytes).unwrap();
        }

        // handle2 should now know handle1's device.
        let found = handle2
            .list_devices()
            .iter()
            .any(|d| hex::encode(&d.device_id) == id1);
        assert!(found, "replayed entries should include handle1's device");
    }
}
